### ISSUE TITLE
Symfony 4 / Symfony Flex support

### ISSUE THREAD

**Issue by chrissnyder2337** [danielanteloagra/AddressableBundle#12]
I am unable to require this bundle in my Symfony 4 / Flex project. 

I believe it does not work because this bundle requires `symfony/symfony` but my project is using flex and thus that dependency conflicts.

**Comment by danielantelo** [comment]
Have removed that dependency and now just require the symfony components directly. Hopefully that should make it flex compatible. This bundle is tested only on Symfony 3.4 LTS. Let me know if it works on a symfony 4 project with flex. (Use version 0.5)
