### ISSUE TITLE
Google Maps API warning: RetiredVersion

### ISSUE THREAD

**Issue by migmolrod** [danielanteloagra/AddressableBundle#14]
I'm getting that error in JS console (browser) when the map loads. The full error message is this:

> Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

This is what the URL says:

RetiredVersion | Warning | You may have supplied a retired version in your script element. The versions 3.0 - 3.30 have been retired, and you might be receiving 3.31 instead. Please update your application to use one of the available versions. See [Versioning \| Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/versions).
-- | -- | --

**Comment by danielantelo** [comment]
was hardcoding v3.25, have removed the version fix, and let it get the latest version which seems to work.
