### ISSUE TITLE
Field is always required

### ISSUE THREAD

**Issue by comur** [danielanteloagra/AddressableBundle#2]
Hi,

Thanks for this great bundle,
I have a small bug, even if I put "not required" the whole type, I have longitude and latitude validators returning me an error The value %value% is not a valid longitude. because value is null.
I will send you a small PR, if you can merge it.

Thanks

**Comment by danielantelo** [comment]
can you PR your fix, and I will merge it down. Thanks. Bundle now updated for symfony 2.8+
